# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4L8lNZgdxkwyoVhiXS4mT2A2n_nPsyR
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf WHAM
!git clone --recursive https://github.com/yohanshin/WHAM.git
# %cd /content/WHAM

!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
!rm -f Miniconda3-latest-Linux-x86_64.sh

import os
os.environ["PATH"] = "/usr/local/miniconda/bin:" + os.environ["PATH"]

!conda --version

!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

!conda create -n wham -y python=3.9

!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main

!conda create -n wham python=3.9 -y

!conda install -n wham -y pytorch=1.11 torchvision=0.12 torchaudio=0.11 cudatoolkit=11.3 -c pytorch
!conda install -n wham -y -c fvcore -c iopath -c conda-forge fvcore iopath

from google.colab import drive
drive.mount('/content/drive')

!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

!conda install -n wham -y pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch

!/usr/local/miniconda/envs/wham/bin/python --version

!/usr/local/miniconda/envs/wham/bin/python -m pip install "numpy<1.24" --force-reinstall

!/usr/local/miniconda/envs/wham/bin/python -c "import torch; print(torch.__version__); print(torch.version.cuda)"

!/usr/local/miniconda/envs/wham/bin/python -c "import numpy; print(numpy.__version__)"

!conda install -n wham -y -c fvcore -c iopath -c conda-forge fvcore iopath

!/usr/local/miniconda/envs/wham/bin/python -m pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html

!/usr/local/miniconda/envs/wham/bin/python -c "import fvcore, iopath, pytorch3d; print('ok')"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!/usr/local/miniconda/envs/wham/bin/python -m pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf chumpy
!git clone https://github.com/mattloper/chumpy.git
# %cd /content/chumpy
!/usr/local/miniconda/envs/wham/bin/python -m pip install --no-build-isolation .

!/usr/local/miniconda/envs/wham/bin/python -c "import chumpy; print('chumpy ok')"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!tail -n +2 requirements.txt > requirements_no_chumpy.txt
!sed -n '1,20p' requirements_no_chumpy.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!/usr/local/miniconda/envs/wham/bin/python -m pip install -r requirements_no_chumpy.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!/usr/local/miniconda/envs/wham/bin/python -m pip install -v -e third-party/ViTPose

!/usr/local/miniconda/envs/wham/bin/python -m pip install mmcv-full==1.5.0 \
  -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html \
  --only-binary=:all:

!/usr/local/miniconda/envs/wham/bin/python -c "import mmcv, mmpose, chumpy; print(mmcv.__version__); print('vitpose ok')"

!/usr/local/miniconda/envs/wham/bin/python -m pip install "numpy<1.24" --force-reinstall

!/usr/local/miniconda/envs/wham/bin/python -c "import numpy, torch, mmcv, mmpose; print(numpy.__version__); print(torch.__version__); print(mmcv.__version__); print('all ok')"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM/third-party/DPVO
!wget -q https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
!unzip -q -o eigen-3.4.0.zip -d thirdparty
!rm -f eigen-3.4.0.zip

!ls thirdparty

!conda install -n wham -y pytorch-scatter=2.0.9 -c rusty1s
!conda install -n wham -y cudatoolkit-dev=11.3.1 -c conda-forge
!conda install -n wham -y -c conda-forge gxx=9.5

!/usr/local/miniconda/envs/wham/bin/python -c "import torch; print(torch.__version__, torch.version.cuda)"
!g++ --version | head -n 1

!ls /usr/local/miniconda/envs/wham/bin/*g++*

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM/third-party/DPVO
!CC=/usr/local/miniconda/envs/wham/bin/x86_64-conda-linux-gnu-cc \
CXX=/usr/local/miniconda/envs/wham/bin/x86_64-conda-linux-gnu-c++ \
CUDA_HOME=/usr/local/miniconda/envs/wham \
/usr/local/miniconda/envs/wham/bin/python -m pip install .

!/usr/local/miniconda/envs/wham/bin/python -c "import dpvo; print('dpvo ok')"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!bash fetch_demo_data.sh

!/usr/local/miniconda/envs/wham/bin/python -m pip install \
  smplx \
  joblib \
  loguru \
  progress \
  scikit-image \
  ultralytics \
  timm \
  xtcocotools \
  json_tricks \
  munkres

!/usr/local/miniconda/envs/wham/bin/python -c "import torch, mmcv, mmpose, smplx, dpvo; print('all core imports ok')"

!/usr/local/miniconda/envs/wham/bin/python -m pip install "numpy<1.24" --force-reinstall

!/usr/local/miniconda/envs/wham/bin/python -c "import numpy; print(numpy.__version__)"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM/third-party/DPVO
!CC=/usr/local/miniconda/envs/wham/bin/x86_64-conda-linux-gnu-cc \
CXX=/usr/local/miniconda/envs/wham/bin/x86_64-conda-linux-gnu-g++ \
CUDA_HOME=/usr/local/miniconda/envs/wham \
/usr/local/miniconda/envs/wham/bin/python -m pip install --no-build-isolation --no-use-pep517 .

!/usr/local/miniconda/envs/wham/bin/python -c "import dpvo; print('dpvo ok')"

!/usr/local/miniconda/envs/wham/bin/python -c "import numpy, torch, mmcv, mmpose, smplx, dpvo; print(numpy.__version__); print(torch.__version__); print('all core imports ok')"

!/usr/local/miniconda/envs/wham/bin/python -m pip install einops yacs tqdm pillow

!/usr/local/miniconda/envs/wham/bin/python -m pip install "imageio[ffmpeg]"

!/usr/local/miniconda/envs/wham/bin/python -c "import imageio_ffmpeg; print('imageio ffmpeg ok')"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM
!PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM MPLBACKEND=Agg /usr/local/miniconda/envs/wham/bin/python demo.py --video examples/IMG_9732.mov --visualize

import os, glob

root = "/content/WHAM/output"
print("output exists:", os.path.exists(root))

files = sorted(glob.glob(root + "/**/*", recursive=True))
for f in files:
    if os.path.isfile(f):
        print(f, os.path.getsize(f), "bytes")

!find /content/WHAM/output -name "*.mp4"

from IPython.display import HTML
import base64
import io

def show_local_mp4_video(file_name, width=720, height=480):
    video_encoded = base64.b64encode(io.open(file_name, 'rb').read()).decode('ascii')
    return HTML(f'''
    <video width="{width}" height="{height}" controls>
        <source src="data:video/mp4;base64,{video_encoded}" type="video/mp4">
    </video>
    ''')

# Show input video
# If visualization fails, try reducing the video resolution and quality as:
# !ffmpeg -i /content/WHAM/examples/IMG_9732.mov -vf "scale=iw/2:ih/2" -vcodec libx264 -crf 30 examples/IMG_9732_mini.mov
# Try same with output videos.

mp4 = '/content/WHAM/examples/IMG_9732.mov'
show_local_mp4_video(mp4, width=360, height=640)



!find /content/WHAM/output -name "*.mp4" 2>/dev/null

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# export MPLBACKEND=Agg
# 
# conda run -n wham python demo.py \
#   --video examples/IMG_9732.mov \
#   --visualize

# Show reconstructed results

mp4 = '/content/WHAM/output/demo/IMG_9732/output.mp4'
show_local_mp4_video(mp4, width=720, height=640)

!find /content/WHAM/output -name "*.mp4"

!find /content/WHAM/output -type f | sort

!ls -R /content/WHAM/output

!find /content/WHAM/output -name "output.mp4"

mp4 = '/content/WHAM/output/demo/IMG_9732/output.mp4'
show_local_mp4_video(mp4, width=960, height=360)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# unset MPLBACKEND
# export MPLBACKEND=Agg
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# 
# /usr/local/miniconda/envs/wham/bin/python demo.py \
#   --video examples/drone_video.mp4 \
#   --calib examples/drone_calib.txt \
#   --visualize \
#   --estimate_local_only 2>&1 | tee /content/WHAM/drone.log

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# mkdir -p /content/WHAM/datasets/3DPW
# mkdir -p /content/WHAM/datasets/RICH
# mkdir -p /content/WHAM/datasets/EMDB
# echo "Created dataset folders"
# find /content/WHAM/datasets -maxdepth 2 -type d

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# mkdir -p /content/WHAM/datasets/3DPW
# mkdir -p /content/WHAM/datasets/RICH
# mkdir -p /content/WHAM/datasets/EMDB
# 
# cp -r /content/drive/MyDrive/WHAM_datasets/3DPW/* /content/WHAM/datasets/3DPW/ 2>/dev/null || true
# cp -r /content/drive/MyDrive/WHAM_datasets/RICH/* /content/WHAM/datasets/RICH/ 2>/dev/null || true
# cp -r /content/drive/MyDrive/WHAM_datasets/EMDB/* /content/WHAM/datasets/EMDB/ 2>/dev/null || true
# 
# echo "Done copying"
# find /content/WHAM/datasets -maxdepth 2 | head -n 100

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# echo "Drive root contents:"
# find /content/drive/MyDrive -maxdepth 2 | head -n 100

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# mkdir -p /content/WHAM/dataset/parsed_data
# echo "Folder created"
# ls /content/WHAM/dataset

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# find /content/drive/MyDrive -maxdepth 3 | grep parsed_data

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# rm -rf /content/WHAM/dataset/parsed_data/*
# echo "Cleaned space"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# mkdir -p /content/WHAM/dataset/parsed_data
# 
# cp /content/drive/MyDrive/parsed_data/3dpw_test_vit.pth /content/WHAM/dataset/parsed_data/
# cp /content/drive/MyDrive/parsed_data/3dpw_val_vit.pth /content/WHAM/dataset/parsed_data/
# cp /content/drive/MyDrive/parsed_data/rich_test_vit.pth /content/WHAM/dataset/parsed_data/
# cp /content/drive/MyDrive/parsed_data/emdb_1_vit.pth /content/WHAM/dataset/parsed_data/
# cp /content/drive/MyDrive/parsed_data/emdb_2_vit.pth /content/WHAM/dataset/parsed_data/

!ls -lh /content/WHAM/dataset/parsed_data

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# unset MPLBACKEND
# export MPLBACKEND=Agg
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# 
# /usr/local/miniconda/envs/wham/bin/python -m lib.eval.evaluate_3dpw \
#   --cfg configs/yamls/demo.yaml \
#   TRAIN.CHECKPOINT checkpoints/wham_vit_bedlam_w_3dpw.pth.tar \
#   2>&1 | tee /content/WHAM/eval_3dpw.log

!tail -n 50 /content/WHAM/eval_3dpw.log

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# find /content/WHAM -iname "SMPL_MALE.pkl" -o -iname "SMPL_FEMALE.pkl" -o -iname "SMPL_NEUTRAL.pkl"

!ls -lh /content/WHAM/dataset/body_models/smpl

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# find /content -iname "SMPL_MALE.pkl" -o -iname "SMPL_FEMALE.pkl"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM/dataset/body_models/smpl
# 
# cp SMPL_NEUTRAL.pkl SMPL_MALE.pkl
# cp SMPL_NEUTRAL.pkl SMPL_FEMALE.pkl
# 
# echo "Files created:"
# ls -lh

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# unset MPLBACKEND
# export MPLBACKEND=Agg
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# 
# /usr/local/miniconda/envs/wham/bin/python -m lib.eval.evaluate_3dpw \
#   --cfg configs/yamls/demo.yaml \
#   TRAIN.CHECKPOINT checkpoints/wham_vit_bedlam_w_3dpw.pth.tar \
#   2>&1 | tee /content/WHAM/eval_3dpw.log

import re

log_path = "/content/WHAM/eval_3dpw.log"

paper_results = {
    "PA-MPJPE": 35.9,
    "MPJPE": 57.8,
    "PVE": 68.7,
    "ACCEL": 6.6
}

with open(log_path, "r", errors="ignore") as f:
    log_text = f.read()

match = re.search(
    r"PA_MPJPE:\s*([0-9.]+),\s*MPJPE:\s*([0-9.]+),\s*PVE:\s*([0-9.]+),\s*ACCEL:\s*([0-9.]+)",
    log_text
)

if match:
    your_results = {
        "PA-MPJPE": float(match.group(1)),
        "MPJPE": float(match.group(2)),
        "PVE": float(match.group(3)),
        "ACCEL": float(match.group(4)),
    }

    print("=" * 65)
    print("               RESULT - 3DPW")
    print("=" * 65)
    print(f"{'Metric':<15}{'Your Result':<15}{'Paper Result':<15}")
    print("-" * 65)

    for key in your_results:
        unit = "mm" if key != "ACCEL" else "m/s²"
        print(f"{key:<15}{your_results[key]:<15.2f}{paper_results[key]:<15.2f} {unit}")

    print("=" * 65)
else:
    print("Metrics not found in log.")

"""## Exp 2

"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/WHAM

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# export MPLBACKEND=Agg
# 
# conda run -n wham python demo.py \
#   --video examples/IMG_9732.mov \
#   --visualize

from glob import glob
import shutil, os

os.makedirs('/content/WHAM/exp2_outputs/original', exist_ok=True)

mp4_files = glob('/content/WHAM/output/**/*.mp4', recursive=True)
print("Found:", mp4_files)

shutil.copy(mp4_files[-1], '/content/WHAM/exp2_outputs/original/output_original.mp4')

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# export MPLBACKEND=Agg
# 
# conda run -n wham python demo.py \
#   --video examples/IMG_9732.mov \
#   --visualize \
#   --estimate_local_only

os.makedirs('/content/WHAM/exp2_outputs/local_only', exist_ok=True)

mp4_files = glob('/content/WHAM/output/**/*.mp4', recursive=True)
print("Found:", mp4_files)

shutil.copy(mp4_files[-1], '/content/WHAM/exp2_outputs/local_only/output_local_only.mp4')

import io, base64
from IPython.display import HTML, display

def show_video(path):
    video = open(path, "rb").read()
    data = base64.b64encode(video).decode()
    return HTML(f'<video width=600 controls><source src="data:video/mp4;base64,{data}" type="video/mp4"></video>')

print("ORIGINAL OUTPUT")
display(show_video('/content/WHAM/exp2_outputs/original/output_original.mp4'))

print("MODIFIED OUTPUT (--estimate_local_only)")
display(show_video('/content/WHAM/exp2_outputs/local_only/output_local_only.mp4'))

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# export MPLBACKEND=Agg
# 
# conda run -n wham python demo.py \
#   --video examples/IMG_9732.mov \
#   --visualize \
#   --run_smplify

from glob import glob
import shutil, os

os.makedirs('/content/WHAM/exp2_outputs/smplify', exist_ok=True)

mp4_files = glob('/content/WHAM/output/**/*.mp4', recursive=True)
print(mp4_files)

shutil.copy(
    '/content/WHAM/output/demo/IMG_9732/output.mp4',
    '/content/WHAM/exp2_outputs/smplify/output_smplify.mp4'
)

print("SMPLify output saved")

print("ORIGINAL OUTPUT")
display(show_video('/content/WHAM/exp2_outputs/original/output_original.mp4'))

print("SMPLIFY OUTPUT")
display(show_video('/content/WHAM/exp2_outputs/smplify/output_smplify.mp4'))

!ls -lh /content/WHAM/output/demo/IMG_9732/

!ffprobe -v error -show_entries format=duration,size -of default=noprint_wrappers=1 /content/WHAM/exp2_outputs/smplify/output_smplify.mp4

!rm -f /content/WHAM/exp2_outputs/smplify/output_smplify.mp4

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/WHAM
# 
# export PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM
# export MPLBACKEND=Agg
# 
# conda run -n wham python demo.py \
#   --video examples/IMG_9732.mov \
#   --visualize \
#   --run_smplify 2>&1 | tee /content/WHAM/smplify_run.log

!tail -n 80 /content/WHAM/smplify_run.log

!mkdir -p /content/WHAM/exp2_outputs/smplify
!cp /content/WHAM/output/demo/IMG_9732/output.mp4 /content/WHAM/exp2_outputs/smplify/output_smplify.mp4

!ffprobe -v error -show_entries format=duration,size -of default=noprint_wrappers=1 /content/WHAM/exp2_outputs/smplify/output_smplify.mp4

from IPython.display import Video

Video('/content/WHAM/exp2_outputs/smplify/output_smplify.mp4', embed=True)

!ls -lh /content/WHAM/checkpoints

!MPLBACKEND=Agg PYTHONPATH=/content/WHAM/third-party/ViTPose:/content/WHAM \
conda run -n wham python -m lib.eval.evaluate_3dpw \
  --cfg configs/yamls/demo.yaml \
  TRAIN.CHECKPOINT checkpoints/wham_vit_w_3dpw.pth.tar \
  2>&1 | tee /content/WHAM/eval_3dpw_modified_checkpoint.log

!tail -n 50 /content/WHAM/eval_3dpw_modified_checkpoint.log

import re
import pandas as pd

logs = {
    "Exp 1 Baseline": "/content/WHAM/eval_3dpw.log",
    "Exp 2 Modified": "/content/WHAM/eval_3dpw_modified_checkpoint.log"
}

def extract_metrics(log_path):
    with open(log_path, "r", errors="ignore") as f:
        text = f.read()

    match = re.search(
        r"PA_MPJPE:\s*([0-9.]+),\s*MPJPE:\s*([0-9.]+),\s*PVE:\s*([0-9.]+),\s*ACCEL:\s*([0-9.]+)",
        text
    )

    if not match:
        raise ValueError(f"Metrics not found in {log_path}")

    return [float(x) for x in match.groups()]

metrics = ["PA-MPJPE", "MPJPE", "PVE", "ACCEL"]

baseline = extract_metrics(logs["Exp 1 Baseline"])
modified = extract_metrics(logs["Exp 2 Modified"])

df = pd.DataFrame({
    "Metric": metrics,
    "Exp 1 Baseline": baseline,
    "Exp 2 Modified": modified,
})

df["Change"] = df["Exp 2 Modified"] - df["Exp 1 Baseline"]
df["Better/Worse"] = df["Change"].apply(lambda x: "Better" if x < 0 else "Worse")

df